---
title: "Misc Modeling Topics"
author: "Geraldo B. Padilla F."
date: "17-03-2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE}
library(tidyverse)
library(modelr)
library(broom)
library(fivethirtyeight)
library(forcats)
library(glm2)
```


## Interaction between continuous and categorical predictors

```{r}
heights <- heights%>%
  mutate(marital_comb = fct_recode(marital,
                              'other' = 'separated',
                              'other' = 'widowed'))

afqt_mod <- lm(afqt~1+marital_comb+height, data = heights)
summary(afqt_mod)

ggplot(heights, aes(x = height, y = afqt)) + 
  geom_jitter(size = 2) + 
  geom_abline(intercept = -26.02, slope = 1.002, size = 1, color = 'blue') + 
  coord_cartesian(xlim = c(0, 90), ylim = c(-30, 105)) +
  ylab("Average Armed Forces Qualification Score") + 
  xlab("Height") +
  theme_bw()

summary(lm(afqt~1+marital_comb+I(height - mean(heights$height)), data = heights)) #capital I = isolate

heights <- heights%>%
  mutate(
    height_cent = height - mean(height)
  )

summary(lm(afqt~1+marital_comb+height_cent, data = heights))

summary(lm(afqt~1+marital_comb*height_cent, data = heights))

model_summary <- augment(lm(afqt~1+marital_comb*height_cent, data = heights))
model_summary

ggplot(model_summary, aes(height_cent, afqt))+
  geom_jitter(alpha = .1)+
  geom_line(aes(x = height_cent, y = .fitted, color = marital_comb), size = 1)+
  ylab('Avg Arm For Quant Score')+
  xlab('Height')+
  theme_bw()
```

## Statistical Assumption Checking with lm()

```{r}
heights2 <- heights %>%
  mutate(
    marital_comb = fct_recode(marital,
          'Other' = 'separated',
          'Other' = 'widowed'))

afqt_mod <- lm(afqt ~ marital_comb + height, data = heights2)
summary(afqt_mod)

heights2 <- heights2 %>%
  mutate(income2 = ifelse(income == 0, .001, income),
         height2 = height - mean(height, na.rm = TRUE),
         education2 = education - mean(education, na.rm = TRUE),
         weight2 = weight - mean(weight, na.rm = TRUE),
         log_income = log(income2))
afqt_alt <- lm(afqt ~ marital_comb + height2 + education2 + 
                 log_income + weight2, data = heights2)
summary(afqt_alt)

plot(afqt_alt)

aug_afqt <- augment(afqt_alt)
aug_afqt

heights_resid <- heights2%>%
  add_residuals(afqt_alt)%>%
  add_predictions(afqt_alt)
heights_resid

filter(heights_resid, abs(resid) > 50)

ggplot(heights_resid, aes(resid))+
  geom_histogram()+
  theme_bw()

ggplot(heights_resid, aes(resid, education2))+
  geom_point(size = 3, alpha = .1)+
  geom_smooth(size = 1, se = F)+
  theme_bw()
```

## Modeling Non-Linear Trends

```{r}
#To create new variables is useful to use mutate() or I() insulate directly into the model syntax.

heights2 <- heights2%>%
  mutate(
    height2_quad = height2^2,
    weight2_quad = weight2^2,
    log_income_quad = log_income^2,
    education2_quad = education2^2)

afqt_alt <- lm(afqt ~ marital_comb + height2 + education2 + 
                 log_income + weight2+height2_quad+weight2_quad+log_income_quad+education2_quad, data = heights2)
summary(afqt_alt)

plot(afqt_alt)

heights2 <- heights2%>%
  mutate(
    afqt2 = ifelse(afqt == 0, .00001, ifelse(afqt == 100, 99.999999, afqt)),
    afqt3 = ifelse(afqt == 0, NA, ifelse(afqt == 100, NA, afqt)),
    afqt_z = qnorm(afqt2/100),
    afqt_z3 = qnorm(afqt3/100),
  )

afqt_alt2 <- lm(afqt_z3 ~1+marital_comb+height2 + education2+log_income+weight2+
                  height2_quad+weight2_quad+log_income_quad+education2_quad,
                data=heights2)
summary(afqt_alt2)

plot(afqt_alt2)
```

## glm() Function

```{r}
titanic <- read_csv('Data/titanic.csv')
names(titanic)

surv_mod <- glm(Survived~1+factor(Pclass)+Fare+Sex+Age, family = binomial(link = 'logit'), data = titanic)
summary(surv_mod)

prob_mod <- titanic%>%
  dplyr::select(Survived, Pclass, Fare, Sex, Age)%>%
  na.omit()%>%
  mutate(
    prob = predict(surv_mod, type = 'response')
  )
prob_mod

#prediction(surv_mod, type = 'response', at = list(Pclass=3, Fare=7.25, Sex = 'male', Age=22))
#If we use prediction from margins package, we will obtain the same result.

ggplot(prob_mod, aes(Age, prob, linetype = Sex))+
  geom_line(aes(color = Sex), size = 1)+
  facet_grid(.~Pclass)+
  xlab('Age')+
  ylab('Probs')+
  theme_bw()
```

