---
title: "11. Reproducible Tables"
author: "Geraldo B. Padilla F."
date: "31-03-2022"
output:
  bookdown::html_document2: default
  bookdown::pdf_document2: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Reproducible Tables

```{r, include=FALSE}
library(kableExtra)
library(formattable)
library(tidyverse)
```

```{r, include=FALSE}
titanic <- read_csv("C:/Users/Lenovo/OneDrive - University of Iowa/PhD portfolio/2. Courses/Spring 2022/PSQF62500EXW Computer Packages for Statistcl Analysis (Brandon LeBeau)/PSQF-6250-Computer-Packages-/Data/titanic.csv")
```


```{r}
titanic_summary <- titanic%>%
  group_by(Pclass)%>%
  summarise(
    avg_age = mean(Age, na.rm = T),
    sd_age = sd(Age, na.rm = T),
    avg_fare = mean(Fare, na.rm = T),
    sd_fare = sd(Fare, na.rm = T),
    min_fare = min(Fare, na.rm = T),
    max_fare = max(Fare, na.rm = T),
    perc_survived = mean(Survived, na.rm = T) * 100,
    n_pass = n())

kable(titanic_summary, digits = 2)

kable(titanic_summary, digits = c(0, 2,2,2,2,1,1,3,0)) #number of decimals

kable(titanic_summary, digits = c(0, 2, 2, 2, 2, 1, 1, 3, 0),
        col.names = c('Class', 'Avg. Age', 'SD Age', 'Avg. Fare', 'SD Fare', 
                      'Min. Fare', 'Max. Fare', '% Survived', 'Number of Passengers')) #colnames transforms each column name

kable(titanic_summary, digits = c(0, 2, 2, 2, 2, 1, 1, 3, 0),
        col.names = c('Class', 'Avg. Age', 'SD Age', 'Avg. Fare', 'SD Fare', 
                      'Min. Fare', 'Max. Fare', '% Survived', 'Number of Passengers'),
        align = 'crrrrrrrr') #Alignment of columns

kable(titanic_summary, digits = c(0, 2, 2, 2, 2, 1, 1, 3, 0),
        col.names = c('Class', 'Avg. Age', 'SD Age', 'Avg. Fare', 'SD Fare', 
                      'Min. Fare', 'Max. Fare', '% Survived', 'Number of Passengers'),
        align = 'crrrrrrrr',
        caption = 'Descriptive statistics of Titanic passengers by ticket class')# main title
```

## Formatting Table with kableExtra

```{r}
tit_kable <- kable(titanic_summary, digits = c(0, 2, 2, 2, 2, 1, 1, 3, 0),
        col.names = c('Class', 'Avg. Age', 'SD Age', 'Avg. Fare', 'SD Fare', 
                      'Min. Fare', 'Max. Fare', '% Survived', 'Number of Passengers'),
        align = 'crrrrrrrr',
        caption = 'Descriptive statistics of Titanic passengers by ticket class')

#Bootstrap table options

kable_styling(tit_kable)

kable_styling(tit_kable, bootstrap_options = 'striped')#fills the background
kable_styling(tit_kable, bootstrap_options = 'hover')#highlights rows
kable_styling(tit_kable, bootstrap_options = 'condensed')#data are downsized
kable_styling(tit_kable, bootstrap_options = 'responsive')#scroll bars
kable_styling(tit_kable, bootstrap_options = 'bordered')#cells
kable_styling(tit_kable, bootstrap_options = c('striped', 'hover', 'condensed', 
                                      'responsive', 'bordered'))

titanic_summary_small <- titanic%>%
  group_by(Pclass)%>%
  summarise(
    avg_age = mean(Age, na.rm = T),
    avg_fare = mean(Fare, na.rm = T),
    perc_survived = mean(Survived) * 100,
    number_passengers = n())

summ_kable <- kable(titanic_summary_small,
      digits = c(0,2,2,3,0),
      colnames = c('Class', 'Avg. Age', 'Avg. Fare',' % Survived', 'Number of Passengers'),
      align = 'crrrr',
      captions = 'Descriptive Statistics of Titanic Passengers by Ticket Class')

kable_styling(summ_kable,
              bootstrap_options = c('striped', 'hover', 'condensed'),
              full_width = F, position = 'float_right')

kable_styling(summ_kable,
              bootstrap_options = c('striped', 'hover', 'condensed'),
              full_width = F, position = 'center', font_size =15)
```

## Column, Row, and Cell Formatting

```{r}
kable(titanic_summary,
      digits = c(0,2,2,2,2,1,1,3,0),
      col.names = c('Class', 'Avg. Age', 'SD Age', 'Avg. Fare', 'SD Fare', 
                      'Min. Fare', 'Max. Fare', '% Survived', 'Number of Passengers'),
      align = 'crrrrrrrr',
      caption = 'Descriptive statistics of Titanic passengers by ticket class')%>%
  kable_styling(
    bootstrap_options = c('striped', 'hover', 'condensed'))%>%
      column_spec(8:9, italic = T, width = '.75in')%>%
      row_spec(0, bold = T, background = '#FF6347')

titanic_summary%>%
  mutate(
    perc_survived = cell_spec(round(perc_survived, 3), #it is applied to the cells of the column
    color = ifelse(perc_survived > 50, '#440154','#FDE725')))%>%
  kable(
    escape = F, #do not escape special characters set before
    digits = c(0,1,1,1,1,2,2,3,0),
    col.names = c('Class', 'Avg. Age', 'SD Age', 'Avg. Fare', 'SD Fare', 
                      'Min. Fare', 'Max. Fare', '% Survived', 'Number of Passengers'),
    align = 'crrrrrrrr',
    caption = 'Descriptive statistics of Titanic passengers by ticket class')%>%
  kable_styling(bootstrap_options = c('striped', 'hover', 'condensed'))%>%
  column_spec(8:9, bold = T, width = '.75in')

titanic_summary%>%
  mutate(
    perc_survived = cell_spec(round(perc_survived, 3),
                              color = ifelse(perc_survived > 50, '#440154','#FDE725')),
    n_pass = color_bar('#FF6347')(n_pass))%>% #it has to be a numeric function
  kable(
    escape = F,
    digits = c(0,1,1,1,1,2,2,3,0),
    col.names = c('Class', 'Avg. Age', 'SD Age', 'Avg. Fare', 'SD Fare', 
                      'Min. Fare', 'Max. Fare', '% Survived', 'Number of Passengers'),
    align = 'crrrrrrrr',
    caption = 'Descriptive statistics of Titanic passengers by ticket class')%>%
  kable_styling(bootstrap_options = c('striped', 'hover', 'condensed'))%>%
  column_spec(8, bold = T, width = '.75in')%>%
  column_spec(9, bold = T)
```

## Grouping Columns or Rows

```{r}
kable(titanic_summary,digits = c(0,1,1,1,1,2,2,3,0),
    col.names = c('Class', 'Avg', 'SD', 'Avg.', 'SD', 
                      'Min.', 'Max.', '% Survived', 'Number of Passengers'),
    align = 'crrrrrrrr',
    caption = 'Descriptive statistics of Titanic passengers by ticket class')%>%
  kable_styling(bootstrap_options = c('striped', 'hover', 'condensed', 'bordered'))%>%
  add_header_above(c('1', 'Age' = 2, 'Fare' = 4, '1', '1'))

titanic_summary_male <- titanic %>%
  filter(Sex == 'male') %>%
  group_by(Pclass) %>%
  summarise(avg_age = mean(Age, na.rm = TRUE),
            avg_fare = mean(Fare, na.rm = TRUE),
            perc_survived = mean(Survived, na.rm = TRUE) * 100,
            number_passengers = n()
  )
titanic_summary_female <- titanic %>%
  filter(Sex == 'female') %>%
  group_by(Pclass) %>%
  summarise(avg_age = mean(Age, na.rm = TRUE),
            avg_fare = mean(Fare, na.rm = TRUE),
            perc_survived = mean(Survived, na.rm = TRUE) * 100,
            number_passengers = n()
  )
titanic_summary_sex <- dplyr::bind_rows(
  titanic_summary_male,
  titanic_summary_female,
  titanic_summary_small
)
titanic_summary_sex
```

```{r cross, echo=F}
kable(titanic_summary_sex,
      digits = c(0, 2, 2, 3, 0),
      col.names = c('Class', 'Avg. Age', 'Avg. Fare', '% Survived', 'Number of Passengers'),
      align = 'crrrr',
      caption = 'Descriptive statistics of Titanic passengers by ticket class')%>%
  kable_styling(bootstrap_options = c('striped', 'hover', 'condensed'), full_width = F)%>%
  kableExtra::group_rows('Male', 1, 3) %>%
  kableExtra::group_rows('Female', 4, 6) %>%
  kableExtra::group_rows('Total', 7, 9)
```

## Cross.referencing Table

Explore Table \@ref(tab:cross) for descriptive statistics by ticket class for males, females, and total numbers.