---
title: "ggplot 2 extensions"
author: "Geraldo B. Padilla F."
date: "25-02-2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Week 3 ggplot2 Extensions

```{r}
library("ggrepel")
library("ggforce")
library("patchwork")
library('palmerpenguins')
library('ggthemes')
library(tidyr)
attach(penguins)
theme_set(theme_bw(base_size = 14))
```

## ggrepel

```{r}
names(penguins)
ggplot(penguins, aes(flipper_length_mm, bill_length_mm))+
  geom_point(size = 2, aes(shape = species))+
  geom_text_repel(aes(label = species))
  xlab('Flipper')+
  ylab('Bill')
#theme(legend.position="none") it removes the legend
  
set.seed(100)
penguins%>%
  group_by(species)%>%
  sample_n(10)%>%
  ggplot(., aes(flipper_length_mm, bill_length_mm))+
  geom_point(size = 4, aes(shape = species))+
  geom_label_repel(aes(label = species))+
  xlab('Flipper')+
  ylab('Bill')
```

## ggforce: it requires complete cases

```{r}
penguins%>%
  drop_na(flipper_length_mm, bill_length_mm)%>%
ggplot(., aes(flipper_length_mm, bill_length_mm))+
  geom_point(aes(shape = species), size = 3)+
  geom_mark_ellipse(aes(fill = species, label = species))
  scale_x_continuous('Flipper')+
  scale_y_continuous('Bill', limits = c(25, 70))

ggplot(penguins, aes(flipper_length_mm, bill_length_mm))+
  geom_point(aes(shape = species, color = species), size = 3)+
  xlab('Flipper')+
  ylab('Bill')+
  facet_zoom(y = species == 'Gentoo')
```

## ggsignif (it requires more evidences)

```{r}
library("ggsignif")
ggplot(penguins, aes(flipper_length_mm, bill_length_mm)) +
  geom_boxplot()+
  geom_signif(comparisons = list(c("Adelie", "Chinstrap")), map_signif_level = TRUE, textsize = 6)
```

## patchwork

```{r}
p1 = ggplot(penguins, aes(flipper_length_mm, bill_length_mm))+
  geom_point(size = 4, aes(color = species, shape = species))+
  xlab('Flipper')+
  ylab('Bill Length')+
  theme(legend.position = 'none', axis.title=element_text(size=10,face="bold"),
        axis.text=element_text(size=6))

p2 = ggplot(penguins, aes(flipper_length_mm, bill_depth_mm))+
  geom_point(size = 4, aes(color = species, shape = species))+
  xlab('Flipper')+
  ylab('Bill Length')+
  theme(legend.position = 'none', axis.title=element_text(size=10,face="bold"),
        axis.text=element_text(size=6))

p3 = ggplot(drop_na(penguins, sex), aes(sex, body_mass_g))+
  geom_violin(aes(fill = species), draw_quantiles = c(.1, .5, .9))+
  xlab('Sex')+
  ylab('Boddy mass')+
  theme(legend.position = 'none', axis.title=element_text(size=10,face="bold"),
        axis.text=element_text(size=6))
p1+p2
p1/p2
p3|(p1/p2)
(p1 + p2) / p3
```