---
title: "Factors"
author: "Geraldo B. Padilla F."
date: "02-03-2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Factor variables in R

```{r libraries}
library(tidyverse)
library(forcats)
library(fivethirtyeight)
```

## Use for factors
```{r}
resp <- c('Disagree', 'Agree', 'Neutral')
sort(resp) # it does not consider any other order than the natural one (numbers or letters)

scale_levels <- c('Strongly Agree', 'Agree', 'Neutral', 'Disagree', 'Strongly Disagree')
resp_fact <- factor(resp, levels = scale_levels) #what are all the possibles values this variable can take?
resp_fact
sort(resp_fact) #now the categories are sorted based on the factor levels

factor(c('disagree', 'Agree', 'Strongly Agree'), levels = scale_levels)
levels(resp_fact) #levels of the factor variable

str(resp_fact)
as.numeric(resp) #words do not have a numerical meaning
as.numeric(resp_fact) #the order of the labels can be translated into numbers
```

## Common Factors Manipulation
1. Reorder factor levels for plotting or table creation
2. Change the levels of the factor

### Reorder Factor Variables
```{r}
weather_check
prop_check_weather <- weather_check%>%
  group_by(region)%>%
  summarise(prop = mean(ck_weather))
prop_check_weather

ggplot(prop_check_weather, aes(region, prop))+
  geom_point()+
  coord_flip()+
  theme_bw()

ggplot(
  na.omit(prop_check_weather),
  aes(prop, fct_reorder(region, desc(prop))))+
  geom_point()+
  theme_bw() #region does not have a natural order, thus we can define an order based on prop.

weather_check%>%
  group_by(hhold_income)%>%
  summarise(prop = mean(ck_weather))%>%
  na.omit()%>%
  ggplot(., aes(
    prop, fct_reorder(hhold_income, prop)))+
  geom_point()+
  theme_bw() #this is not a good practice because the categorical variable has a natural order.

#flying$recline_eliminate <- as.numeric(flying$recline_eliminate)

summary(flying$recline_eliminate)
mean(flying$recline_eliminate, na.rm = T) #prop of respondents that believe the reclining the chair while flying should be eliminated

flying%>%
  na.omit()%>%
  group_by(location)%>%
  summarise(prop = mean(recline_eliminate)) #Do these proportions differ by the location?

flying%>%
  na.omit()%>%
  group_by(location)%>%
  summarise(prop = mean(recline_eliminate))%>%
  ggplot(., aes(prop, fct_reorder(location, prop)))+
           geom_point()+
           theme_bw() #Create a graphic that captures this relationship
```

### Rename Factors

```{r}
levels(weather_check$age)
table(weather_check$age)

weather_check%>%
  mutate(
    age_recode = fct_recode(age,
                            '18 to 29' = "18 - 29", #the original names have to be the same
                            '30 to 44' = "30 - 44", 
                            '45 to 59' = "45 - 59"))%>%
  count(age_recode) #the same category remains the same

levels(weather_check$ck_weather_watch)

weather_check%>%
  mutate(watch_recode = fct_recode(ck_weather_watch,
    'Unlikely' = "Very unlikely",
    'Unlikely' = "Somewhat unlikely",
    'Likely'= "Somewhat likely",
    'Likely'= "Very likely"))%>%
  count(watch_recode)

weather_check%>%
  mutate(region = fct_lump(region, n = 5))%>% #n specifies the number of unique categories. The rest will be lumped into a Other category
  count(region, sort = T)#sort is an alternative to arrange from dplyer

summary(flying$children_under_18)
summary(flying$baby)

flying%>%
  na.omit()%>%
  mutate(baby_rude = fct_recode(baby, 
                                'Yes' = 'Very',
                                'Yes' = 'Somewhat',
                                'No' = 'No'))%>%
  group_by(children_under_18)%>%
  count(children_under_18, baby_rude)%>%
  mutate(prop = n/sum(n))
```

## Working with Character Strings
```{r}
library(stringr)
```

```{r}
string <- c('Iowa City', 'Cedar Rapids', 'Des Moines', 'IA')
str_length(string) #how long text attributes are?

str_c('Iowa City', 'Cedar Rapids', 'Des Moines', 'IA')
str_c(c('Iowa City', 'Cedar Rapids', 'Des Moines'), 'IA') #it pastes the last label to each of the concatenated labels
str_c(c('Iowa City', 'Cedar Rapids', 'Des Moines'), 'IA', sep = ',')
str_c(c('Iowa City', 'Cedar Rapids', 'Des Moines'), collapse = ', ')
#this is useful to combine multiple columns in the data (labels)

str_sub(c('Iowa City', 'Cedar Rapids', 'Des Moines'), 1, 5) #it is useful for subsetting strings by location. Numbers represents: take from this up to this.
str_sub(c('Iowa City', 'Cedar Rapids', 'Des Moines'), -6, -1)
```

## Introduction to Regular Expressions

```{r}
x <- c('Iowa City', 'Cedar Rapids', 'Des Moines')
str_view(x, 'City')
str_view(x, 'city')
str_view(x, regex('city', ignore_case = T))#it looks for the word regardless of the lower or upper case

x <- c('Iowa City', 'Des Moines, Iowa')
str_view(x, '^Iowa')
str_view(x, 'Iowa$')

#? 0 or 1 match
#+ 1 or more
#* 0 or more
sounds <- c('baaaa', 'ssss', 'moo', 'buzz', 'purr', 'baaa')
str_view(sounds, 'aa?')
str_view(sounds, 'a+')
str_view(sounds, 'rrr+') #the mark applies only to the last character

str_view(sounds, 'r{2}')
#[n] match exactly n
#{n, } match n or more
#{, m} match at most m
#{n, m} match between n and m

str_trim(sounds)
string <- "\n\nString with trailing and leading white space\n\n"
str_trim(string)
```

## Regular Expression Functions

```{r}
x<- c('Iowa City, Iowa', 'Cedar Rapids, IA', 'Des Moines, Iowa', 'Waterloo, IA', 'Rochester, Minnesota')

str_detect(x, 'Iowa$') #Dollar signs stands for matching the character at the end of the strings
str_detect(x, 'Iowa$|IA$')
mean(str_detect(x, 'Iowa$|IA$'))

str_count(x, 'Iowa$|IA$')
str_count(x, 'Iowa|IA')

str_replace(x, 'Iowa$', 'IA') #This function takes two arguments, first the text to be matched and second the text the match should be changed to.
str_replace(x, 'Iowa', 'IA')
str_replace_all(x, 'Iowa', 'IA')

str_extract(x, 'Minnesota')
str_extract(x, '^.*,') #At the start of the string (^) match any character (.) multiples times (*), followed by a comma(,).

str_split(x, ', ', simplify = T)#The str_split function will remove the delimiter that it used to split on.
```

## Real-World Example

```{r}
library(readr)
library(lubridate)
```


```{r}
ufo <- read_csv('Data/ufo.csv')

time <- str_split(ufo$Duration, ' ', simplify = T); time
time <- data.frame(time)
time <- select(time, X1, X2)
colnames(time) <- c('time', 'unit')
cbind(ufo, time)

ufo %>%
  mutate(
    num_colors = str_count(Summary, 'white|green|red|blue|orange|purple|yellow'))

head(ufo$`Date / Time`)

ufo <- ufo %>%
  mutate(converted_date = mdy_hm(`Date / Time`))

ufo %>%
  mutate(
    year = year(converted_date),
    month = month(converted_date),
    day = day(converted_date),
    hour = hour(converted_date),
    minute = minute(converted_date),
    month_label_abbr = month(converted_date, label = TRUE),
    wday_abbr = wday(converted_date, label = TRUE),
    month_label = month(converted_date, label = TRUE, abbr = FALSE),
    wday = wday(converted_date, label = TRUE, abbr = FALSE)
  )
```